### ISSUE TITLE
Dialog have to be in memory cache

### ISSUE THREAD

**Issue by nichman** [QuickBlox/q-municate-services-ios#179]
Hi,

I used QMChatViewController to send message. I can send the photo but It crash!! when i send text message. I can't figure out why it crash. I checked all parameter There aren't null. This is an error log. Thanks a lot.

> 2016-04-11 15:31:54.648 Boonthavorn[1994:24670] **\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Dialog have to be in memory cache!'
> **\* First throw call stack:
> (
>  0   CoreFoundation                      0x00000001074f7d85 **exceptionPreprocess + 165
>  1   libobjc.A.dylib                     0x0000000106f6bdeb objc_exception_throw + 48
>  2   CoreFoundation                      0x00000001074f7bea +[NSException raise:format:arguments:] + 106
>  3   Foundation                          0x0000000106a7ad5a -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
>  4   Boonthavorn                         0x000000010229af10 -[QMChatService sendMessage:toDialogID:saveToHistory:saveToStorage:completion:] + 896
>  5   Boonthavorn                         0x000000010218382e -[LiveChatViewController didPressSendButton:withMessageText:senderId:senderDisplayName:date:] + 1774
>  6   Boonthavorn                         0x000000010223ab94 -[QMChatViewController messagesInputToolbar:didPressRightBarButton:] + 276
>  7   Boonthavorn                         0x000000010224397d -[QMInputToolbar rightBarButtonPressed:] + 93
>  8   UIKit                               0x0000000104ef4a8d -[UIApplication sendAction:to:from:forEvent:] + 92
>  9   UIKit                               0x0000000105067e67 -[UIControl sendAction:to:forEvent:] + 67
>  10  UIKit                               0x0000000105068143 -[UIControl _sendActionsForEvents:withEvent:] + 327
>  11  UIKit                               0x0000000105067263 -[UIControl touchesEnded:withEvent:] + 601
>  12  UIKit                               0x0000000104f6799f -[UIWindow _sendTouchesForEvent:] + 835
>  13  UIKit                               0x0000000104f686d4 -[UIWindow sendEvent:] + 865
>  14  UIKit                               0x0000000104f13dc6 -[UIApplication sendEvent:] + 263
>  15  UIKit                               0x0000000104eed553 _UIApplicationHandleEventQueue + 6660
>  16  CoreFoundation                      0x000000010741d301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
>  17  CoreFoundation                      0x000000010741322c __CFRunLoopDoSources0 + 556
>  18  CoreFoundation                      0x00000001074126e3 __CFRunLoopRun + 867
>  19  CoreFoundation                      0x00000001074120f8 CFRunLoopRunSpecific + 488
>  20  GraphicsServices                    0x00000001089cdad2 GSEventRunModal + 161
>  21  UIKit                               0x0000000104ef2f09 UIApplicationMain + 171
>  22  Boonthavorn                         0x00000001021f33bf main + 111
>  23  libdyld.dylib                       0x0000000107a7892d start + 1
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb)

**Comment by ghost** [comment]
Hi @nichman,
Could you please provide full logs?
Have you changed code for services?

**Comment by nichman** [comment]
Hi @VitaliyGuru ,

Thank you for response my  issue. I found the cause of this problem. I forgot to initialize lastActivityDate. Sorry for my fault. 

> [ServicesManager instance].lastActivityDate

**Comment by ghost** [comment]
@nichman , I am glad to hear that your problem has been resolved.

**Comment by Dhiru-Dev** [comment]
i am facing the same problem , can you please guide me ,,, after intializing the Last

`[ServicesManager instance].lastActivityDate`

 Did not solved my problem 

```
 *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Dialog have to be in memory cache!'
*** First throw call stack:
(
    0   CoreFoundation                      0x000000011177ce65 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x0000000110ec9deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000011177ccca +[NSException raise:format:arguments:] + 106
    3   Foundation                          0x0000000110b154de -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 198
    4   APP                              0x000000010c5e9aaf -[QMChatService sendMessage:toDialogID:saveToHistory:saveToStorage:completion:] + 911
    5   APP                              0x000000010c552d9b -[ChatVC didPressSendButton:withMessageText:senderId:senderDisplayName:date:] + 1147
    6   APp                            0x000000010c4851e4 -[QMChatViewController messagesInputToolbar:didPressRightBarButton:] + 276
    7   App                              0x000000010c46c26d -[QMInputToolbar rightBarButtonPressed:] + 93
    8   UIKit                               0x000000010eb30194 -[UIApplication sendAction:to:from:forEvent:] + 92
    9   UIKit                               0x000000010ec9f6fc -[UIControl sendAction:to:forEvent:] + 67
    10  UIKit                               0x000000010ec9f9c8 -[UIControl _sendActionsForEvents:withEvent:] + 311
    11  UIKit                               0x000000010ec9eaf8 -[UIControl touchesEnded:withEvent:] + 601
    12  UIKit                               0x000000010eb9f49b -[UIWindow _sendTouchesForEvent:] + 835
    13  UIKit                               0x000000010eba01d0 -[UIWindow sendEvent:] + 865
    14  UIKit                               0x000000010eb4eb66 -[UIApplication sendEvent:] + 263
    15  UIKit                               0x000000010eb28d97 _UIApplicationHandleEventQueue + 6844
    16  CoreFoundation                      0x00000001116a8a31 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
    17  CoreFoundation                      0x000000011169e95c __CFRunLoopDoSources0 + 556
    18  CoreFoundation                      0x000000011169de13 __CFRunLoopRun + 867
    19  CoreFoundation                      0x000000011169d828 CFRunLoopRunSpecific + 488
    20  GraphicsServices                    0x00000001132e9ad2 GSEventRunModal + 161
    21  UIKit                               0x000000010eb2e610 UIApplicationMain + 171
    22  App                              0x000000010c4ba3bf main + 111
    23  libdyld.dylib                       0x000000011236192d start + 1
    24  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```
