### ISSUE TITLE
'QMServicesManager.h' file not found

### ISSUE THREAD

**Issue by UtkuDalmaz** [QuickBlox/q-municate-services-ios#249]
After latest pod update, i am getting this error
`'QMServicesManager.h' file not found`

In a swift project and in an objective-c library, i use
`#import "QMServicesManager.h"`

after latest pod update i started using use_frameworks! but now i get this error
'QMServicesManager.h' file not found

Any idea ?

**Comment by Raikerian** [comment]
Hi,

Thank you for reporting the issue. We are working on fix and will post update as soon as possible.

**Comment by Raikerian** [comment]
@UtkuDalmaz I was able to fix the issue. We are planning to make a release later this week.

**Comment by Raikerian** [comment]
Check out our latest version of QMServices (0.4.4) and QMChatViewController (0.3.10). We have fixed all issues with frameworks pods. Check our updated samples with use_frameworks! pods flag on installation tips: https://github.com/QuickBlox/quickblox-ios-sdk

**Comment by UtkuDalmaz** [comment]
Still having the problem even though i update the latest

<img width="712" alt="screen shot 2016-08-15 at 14 17 04" src="https://cloud.githubusercontent.com/assets/2130592/17663157/236ac262-62f3-11e6-8d35-f77f75d9d5e8.png">

**Comment by UtkuDalmaz** [comment]
Hey guys any idea on this bug?

**Comment by Raikerian** [comment]
Have you tried importing using '<>' ?

**Comment by UtkuDalmaz** [comment]
it says 
![screen shot 2016-09-22 at 11 33 18](https://cloud.githubusercontent.com/assets/2130592/18741533/6c9e4782-80b8-11e6-9b69-4310cf20e130.png)

**Comment by Raikerian** [comment]
Please show your podfile content.

**Comment by UtkuDalmaz** [comment]
platform :ios, “9.0”

use_frameworks!

target “Jemiyet” do
pod 'SDWebImage'
pod 'SVProgressHUD'
pod 'TWMessageBarManager'
pod 'QMServices'
pod 'Fabric'
pod 'Crashlytics'
pod 'Bolts'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'ALCameraViewController', '1.2.5'
pod 'Agrume'
pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift'
pod 'SwiftyJSON'
pod 'ImageScrollView'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end

**Comment by Raikerian** [comment]
Import QMServices like this:

``` objc
#import "QMServices.h"
```

Checkout our [sample-chat projects](https://github.com/QuickBlox/quickblox-ios-sdk) to see more in-depth usage.

**Comment by UtkuDalmaz** [comment]
Doesn't work man, it says : 'QMServices.h' file not found 
This happened after the framework update :(

**Comment by Raikerian** [comment]
Have you checked our samples projects?

**Comment by UtkuDalmaz** [comment]
"#import < QMServices/QMServicesManager.h >" is fixed the problem

**Comment by Raikerian** [comment]
And what were you doing before?

**Comment by UtkuDalmaz** [comment]
I am having Warning

/Users/utkudalmaz/Developer/Jemiyet/Pods/QMServices/QMBaseService/QMBaseService/QMBaseService.h:23:1: Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'

just to inform you
